project_id = "byodznmmqxyzzcidfwse"

[functions.fashion-chat]
verify_jwt = false

[functions.send-otp-email]
verify_jwt = false

[functions.twilio-send-otp]
verify_jwt = false

[functions.twilio-verify-otp]
verify_jwt = false